# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dffe0af1-a110-4b32-9c22-ac820ab0b727";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A825-EC2F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    
  fileSystems."/smnt" = 
    {
      # 从Disks中复制的UUID，比设备名更稳定
      device = "/dev/disk/by-uuid/d6426915-34a0-437b-90c9-c9e04f625914";
      fsType = "ext4";
      # 挂载选项：defaults（默认）+ noatime（提升性能）
      options = [ "defaults" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c20118d-1d75-40a1-8901-18df77dc6b24"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
